# This is the Supabase configuration file

[auth]
# URL site et redirections
site_url = "https://abienergie.github.io/Simulator"
additional_redirect_urls = ["https://abienergie.github.io/Simulator/#/oauth/callback"]

[auth.email]
enable_signup = false
double_confirm_changes = false
enable_confirmations = false

[functions]
[functions.enedis-auth]
verify_jwt = false